export { validarAcceso } from './funcionesEjer5.js';
export { calcularPromedio } from './funcionesEjer3.js';
export { compare, ordenAsc, ordenDesc } from './funcionesEjer4.js';
export { validar } from './funcionesEjer1.js';
export { calcularAreaPerimetro } from './funcionesEjer2.js';
export { generarTablaMultiplicar } from './funcionesEjer6.js';
export { registrarProductos } from './modulos/funcionesEjer7';
export {validar} from './funcionesEjer8.js';
export { procesarPagos } from './funcionesEjer9.js';
export {fusionarUsuarios} from './funcionesEjer10.js';